# Generated by Django 5.2.7 on 2025-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text="Désigne si l'utilisateur est un admin de la plateforme (accès global)"),
        ),
    ]
