# Generated by Django 5.2.7 on 2025-11-05 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_register', 'User Register'), ('login_failed', 'Login Failed'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('role_changed', 'Role Changed'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('challenge_created', 'Challenge Created'), ('challenge_updated', 'Challenge Updated'), ('challenge_deleted', 'Challenge Deleted'), ('solution_submitted', 'Solution Submitted'), ('solution_validated', 'Solution Validated'), ('admin_action', 'Admin Action')], max_length=50)),
                ('target_model', models.CharField(blank=True, help_text="Type de l'objet ciblé (User, Challenge, etc.)", max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, help_text="ID de l'objet ciblé", max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text="Description lisible de l'action")),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Détails des changements (avant/après)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent du navigateur')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('target_user', models.ForeignKey(blank=True, help_text="User cible de l'action (si applicable)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text="User qui a effectué l'action (null si action système)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
    ]
