# Generated by Django 5.2.7 on 2025-11-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=10),
        ),
    ]
