# Generated by Django 5.2.7 on 2025-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_component_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('BUTTON', 'Button'), ('CARD', 'Card'), ('INPUT', 'Input'), ('MODAL', 'Modal'), ('ACCORDION', 'Accordion'), ('SIDEBAR', 'Sidebar'), ('NAVBAR', 'Navbar'), ('DROPDOWN', 'Dropdown'), ('CAROUSEL', 'Carousel'), ('CHART', 'Chart'), ('TABLE', 'Table'), ('TOAST', 'Toast'), ('TOGGLE', 'Toggle'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select'), ('ALERT', 'Alert'), ('BADGE', 'Badge'), ('BREADCRUMB', 'Breadcrumb'), ('FORM', 'Form'), ('PAGINATION', 'Pagination'), ('PROGRESS', 'Progress')], max_length=50),
        ),
    ]
